version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: ark_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ark_dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql

volumes:
  postgres_data_new:
